### ISSUE TITLE
Honor

### ISSUE THREAD

**Issue by Lokhillo** [microsoft/vscode-custom-data#91]
`npm i @vscode/web-custom-data`
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-custom-data/pull/87
- [ ] https://github.com/microsoft/vscode-custom-data/issues/90
- [ ] https://github.com/microsoft/vscode-custom-data/issues/85
- [ ] https://github.com/microsoft/vscode-custom-data/pull/84
- [ ] https://github.com/microsoft/vscode-custom-data/issues/82
- [ ] https://github.com/microsoft/vscode-custom-data/issues/76
- [ ] https://github.com/microsoft/vscode-custom-data/issues/89
- [ ] https://github.com/microsoft/vscode-custom-data/pull/88
- [ ] https://github.com/microsoft/vscode-custom-data/issues/77
- [ ] https://github.com/microsoft/vscode-custom-data/pull/75
- [ ] https://github.com/microsoft/vscode-custom-data/pull/83
- [x] yarn update-sources
```
